// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.2 (commit 4b41cf3d71aa85cd4e75c96cbb54324481ee0b27).

#![allow(unused, clippy::all)]
use super::alert_type::Alert;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `alert`.
///
/// Obtain a handle from the [`AlertTableAccess::alert`] method on [`super::RemoteTables`],
/// like `ctx.db.alert()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.alert().on_insert(...)`.
pub struct AlertTableHandle<'ctx> {
    imp: __sdk::TableHandle<Alert>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `alert`.
///
/// Implemented for [`super::RemoteTables`].
pub trait AlertTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`AlertTableHandle`], which mediates access to the table `alert`.
    fn alert(&self) -> AlertTableHandle<'_>;
}

impl AlertTableAccess for super::RemoteTables {
    fn alert(&self) -> AlertTableHandle<'_> {
        AlertTableHandle {
            imp: self.imp.get_table::<Alert>("alert"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct AlertInsertCallbackId(__sdk::CallbackId);
pub struct AlertDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for AlertTableHandle<'ctx> {
    type Row = Alert;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Alert> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = AlertInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AlertInsertCallbackId {
        AlertInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: AlertInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = AlertDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AlertDeleteCallbackId {
        AlertDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: AlertDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Alert>("alert");
    _table.add_unique_constraint::<i64>("id", |row| &row.id);
}
pub struct AlertUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for AlertTableHandle<'ctx> {
    type UpdateCallbackId = AlertUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> AlertUpdateCallbackId {
        AlertUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: AlertUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Alert>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Alert>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `alert`,
/// which allows point queries on the field of the same name
/// via the [`AlertIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.alert().id().find(...)`.
pub struct AlertIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Alert, i64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> AlertTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `alert`.
    pub fn id(&self) -> AlertIdUnique<'ctx> {
        AlertIdUnique {
            imp: self.imp.get_unique_constraint::<i64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> AlertIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &i64) -> Option<Alert> {
        self.imp.find(col_val)
    }
}
