// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.2 (commit 4b41cf3d71aa85cd4e75c96cbb54324481ee0b27).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AssignDriverToShipmentArgs {
    pub shipment_id: i32,
    pub driver_id: u64,
}

impl From<AssignDriverToShipmentArgs> for super::Reducer {
    fn from(args: AssignDriverToShipmentArgs) -> Self {
        Self::AssignDriverToShipment {
            shipment_id: args.shipment_id,
            driver_id: args.driver_id,
        }
    }
}

impl __sdk::InModule for AssignDriverToShipmentArgs {
    type Module = super::RemoteModule;
}

pub struct AssignDriverToShipmentCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `assign_driver_to_shipment`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait assign_driver_to_shipment {
    /// Request that the remote module invoke the reducer `assign_driver_to_shipment` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_assign_driver_to_shipment`] callbacks.
    fn assign_driver_to_shipment(&self, shipment_id: i32, driver_id: u64) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `assign_driver_to_shipment`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`AssignDriverToShipmentCallbackId`] can be passed to [`Self::remove_on_assign_driver_to_shipment`]
    /// to cancel the callback.
    fn on_assign_driver_to_shipment(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &i32, &u64) + Send + 'static,
    ) -> AssignDriverToShipmentCallbackId;
    /// Cancel a callback previously registered by [`Self::on_assign_driver_to_shipment`],
    /// causing it not to run in the future.
    fn remove_on_assign_driver_to_shipment(&self, callback: AssignDriverToShipmentCallbackId);
}

impl assign_driver_to_shipment for super::RemoteReducers {
    fn assign_driver_to_shipment(&self, shipment_id: i32, driver_id: u64) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "assign_driver_to_shipment",
            AssignDriverToShipmentArgs {
                shipment_id,
                driver_id,
            },
        )
    }
    fn on_assign_driver_to_shipment(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &i32, &u64) + Send + 'static,
    ) -> AssignDriverToShipmentCallbackId {
        AssignDriverToShipmentCallbackId(self.imp.on_reducer(
            "assign_driver_to_shipment",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer:
                                super::Reducer::AssignDriverToShipment {
                                    shipment_id,
                                    driver_id,
                                },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, shipment_id, driver_id)
            }),
        ))
    }
    fn remove_on_assign_driver_to_shipment(&self, callback: AssignDriverToShipmentCallbackId) {
        self.imp
            .remove_on_reducer("assign_driver_to_shipment", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `assign_driver_to_shipment`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_assign_driver_to_shipment {
    /// Set the call-reducer flags for the reducer `assign_driver_to_shipment` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn assign_driver_to_shipment(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_assign_driver_to_shipment for super::SetReducerFlags {
    fn assign_driver_to_shipment(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("assign_driver_to_shipment", flags);
    }
}
