// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.2 (commit 4b41cf3d71aa85cd4e75c96cbb54324481ee0b27).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::lat_long_location_type::LatLongLocation;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CreateDriverArgs {
    pub id: u64,
    pub status: String,
    pub current_location: LatLongLocation,
}

impl From<CreateDriverArgs> for super::Reducer {
    fn from(args: CreateDriverArgs) -> Self {
        Self::CreateDriver {
            id: args.id,
            status: args.status,
            current_location: args.current_location,
        }
    }
}

impl __sdk::InModule for CreateDriverArgs {
    type Module = super::RemoteModule;
}

pub struct CreateDriverCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `create_driver`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait create_driver {
    /// Request that the remote module invoke the reducer `create_driver` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_create_driver`] callbacks.
    fn create_driver(
        &self,
        id: u64,
        status: String,
        current_location: LatLongLocation,
    ) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `create_driver`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`CreateDriverCallbackId`] can be passed to [`Self::remove_on_create_driver`]
    /// to cancel the callback.
    fn on_create_driver(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &u64, &String, &LatLongLocation)
            + Send
            + 'static,
    ) -> CreateDriverCallbackId;
    /// Cancel a callback previously registered by [`Self::on_create_driver`],
    /// causing it not to run in the future.
    fn remove_on_create_driver(&self, callback: CreateDriverCallbackId);
}

impl create_driver for super::RemoteReducers {
    fn create_driver(
        &self,
        id: u64,
        status: String,
        current_location: LatLongLocation,
    ) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "create_driver",
            CreateDriverArgs {
                id,
                status,
                current_location,
            },
        )
    }
    fn on_create_driver(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &u64, &String, &LatLongLocation)
            + Send
            + 'static,
    ) -> CreateDriverCallbackId {
        CreateDriverCallbackId(self.imp.on_reducer(
            "create_driver",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer:
                                super::Reducer::CreateDriver {
                                    id,
                                    status,
                                    current_location,
                                },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, id, status, current_location)
            }),
        ))
    }
    fn remove_on_create_driver(&self, callback: CreateDriverCallbackId) {
        self.imp.remove_on_reducer("create_driver", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `create_driver`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_create_driver {
    /// Set the call-reducer flags for the reducer `create_driver` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn create_driver(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_create_driver for super::SetReducerFlags {
    fn create_driver(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("create_driver", flags);
    }
}
