// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.2 (commit 4b41cf3d71aa85cd4e75c96cbb54324481ee0b27).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::lat_long_location_type::LatLongLocation;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CreateShipmentArgs {
    pub id: i32,
    pub content: String,
    pub min_temp: f32,
    pub max_temp: f32,
    pub start_location: LatLongLocation,
    pub end_location: LatLongLocation,
    pub sender_information: String,
    pub receiver_information: String,
}

impl From<CreateShipmentArgs> for super::Reducer {
    fn from(args: CreateShipmentArgs) -> Self {
        Self::CreateShipment {
            id: args.id,
            content: args.content,
            min_temp: args.min_temp,
            max_temp: args.max_temp,
            start_location: args.start_location,
            end_location: args.end_location,
            sender_information: args.sender_information,
            receiver_information: args.receiver_information,
        }
    }
}

impl __sdk::InModule for CreateShipmentArgs {
    type Module = super::RemoteModule;
}

pub struct CreateShipmentCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `create_shipment`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait create_shipment {
    /// Request that the remote module invoke the reducer `create_shipment` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_create_shipment`] callbacks.
    fn create_shipment(
        &self,
        id: i32,
        content: String,
        min_temp: f32,
        max_temp: f32,
        start_location: LatLongLocation,
        end_location: LatLongLocation,
        sender_information: String,
        receiver_information: String,
    ) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `create_shipment`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`CreateShipmentCallbackId`] can be passed to [`Self::remove_on_create_shipment`]
    /// to cancel the callback.
    fn on_create_shipment(
        &self,
        callback: impl FnMut(
                &super::ReducerEventContext,
                &i32,
                &String,
                &f32,
                &f32,
                &LatLongLocation,
                &LatLongLocation,
                &String,
                &String,
            ) + Send
            + 'static,
    ) -> CreateShipmentCallbackId;
    /// Cancel a callback previously registered by [`Self::on_create_shipment`],
    /// causing it not to run in the future.
    fn remove_on_create_shipment(&self, callback: CreateShipmentCallbackId);
}

impl create_shipment for super::RemoteReducers {
    fn create_shipment(
        &self,
        id: i32,
        content: String,
        min_temp: f32,
        max_temp: f32,
        start_location: LatLongLocation,
        end_location: LatLongLocation,
        sender_information: String,
        receiver_information: String,
    ) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "create_shipment",
            CreateShipmentArgs {
                id,
                content,
                min_temp,
                max_temp,
                start_location,
                end_location,
                sender_information,
                receiver_information,
            },
        )
    }
    fn on_create_shipment(
        &self,
        mut callback: impl FnMut(
                &super::ReducerEventContext,
                &i32,
                &String,
                &f32,
                &f32,
                &LatLongLocation,
                &LatLongLocation,
                &String,
                &String,
            ) + Send
            + 'static,
    ) -> CreateShipmentCallbackId {
        CreateShipmentCallbackId(self.imp.on_reducer(
            "create_shipment",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer:
                                super::Reducer::CreateShipment {
                                    id,
                                    content,
                                    min_temp,
                                    max_temp,
                                    start_location,
                                    end_location,
                                    sender_information,
                                    receiver_information,
                                },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(
                    ctx,
                    id,
                    content,
                    min_temp,
                    max_temp,
                    start_location,
                    end_location,
                    sender_information,
                    receiver_information,
                )
            }),
        ))
    }
    fn remove_on_create_shipment(&self, callback: CreateShipmentCallbackId) {
        self.imp.remove_on_reducer("create_shipment", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `create_shipment`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_create_shipment {
    /// Set the call-reducer flags for the reducer `create_shipment` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn create_shipment(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_create_shipment for super::SetReducerFlags {
    fn create_shipment(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("create_shipment", flags);
    }
}
