// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.2 (commit 4b41cf3d71aa85cd4e75c96cbb54324481ee0b27).

#![allow(unused, clippy::all)]
use super::lat_long_location_type::LatLongLocation;
use super::transporter_type::Transporter;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `driver`.
///
/// Obtain a handle from the [`DriverTableAccess::driver`] method on [`super::RemoteTables`],
/// like `ctx.db.driver()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.driver().on_insert(...)`.
pub struct DriverTableHandle<'ctx> {
    imp: __sdk::TableHandle<Transporter>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `driver`.
///
/// Implemented for [`super::RemoteTables`].
pub trait DriverTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`DriverTableHandle`], which mediates access to the table `driver`.
    fn driver(&self) -> DriverTableHandle<'_>;
}

impl DriverTableAccess for super::RemoteTables {
    fn driver(&self) -> DriverTableHandle<'_> {
        DriverTableHandle {
            imp: self.imp.get_table::<Transporter>("driver"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct DriverInsertCallbackId(__sdk::CallbackId);
pub struct DriverDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for DriverTableHandle<'ctx> {
    type Row = Transporter;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Transporter> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = DriverInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> DriverInsertCallbackId {
        DriverInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: DriverInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = DriverDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> DriverDeleteCallbackId {
        DriverDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: DriverDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Transporter>("driver");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}
pub struct DriverUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for DriverTableHandle<'ctx> {
    type UpdateCallbackId = DriverUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> DriverUpdateCallbackId {
        DriverUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: DriverUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Transporter>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Transporter>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `driver`,
/// which allows point queries on the field of the same name
/// via the [`DriverIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.driver().id().find(...)`.
pub struct DriverIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Transporter, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> DriverTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `driver`.
    pub fn id(&self) -> DriverIdUnique<'ctx> {
        DriverIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> DriverIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Transporter> {
        self.imp.find(col_val)
    }
}
