// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.2 (commit 4b41cf3d71aa85cd4e75c96cbb54324481ee0b27).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ProcessSensorReadingArgs {
    pub shipment_id: i32,
    pub timestamp: __sdk::Timestamp,
    pub temperature: f32,
}

impl From<ProcessSensorReadingArgs> for super::Reducer {
    fn from(args: ProcessSensorReadingArgs) -> Self {
        Self::ProcessSensorReading {
            shipment_id: args.shipment_id,
            timestamp: args.timestamp,
            temperature: args.temperature,
        }
    }
}

impl __sdk::InModule for ProcessSensorReadingArgs {
    type Module = super::RemoteModule;
}

pub struct ProcessSensorReadingCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `process_sensor_reading`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait process_sensor_reading {
    /// Request that the remote module invoke the reducer `process_sensor_reading` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_process_sensor_reading`] callbacks.
    fn process_sensor_reading(
        &self,
        shipment_id: i32,
        timestamp: __sdk::Timestamp,
        temperature: f32,
    ) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `process_sensor_reading`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`ProcessSensorReadingCallbackId`] can be passed to [`Self::remove_on_process_sensor_reading`]
    /// to cancel the callback.
    fn on_process_sensor_reading(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &i32, &__sdk::Timestamp, &f32)
            + Send
            + 'static,
    ) -> ProcessSensorReadingCallbackId;
    /// Cancel a callback previously registered by [`Self::on_process_sensor_reading`],
    /// causing it not to run in the future.
    fn remove_on_process_sensor_reading(&self, callback: ProcessSensorReadingCallbackId);
}

impl process_sensor_reading for super::RemoteReducers {
    fn process_sensor_reading(
        &self,
        shipment_id: i32,
        timestamp: __sdk::Timestamp,
        temperature: f32,
    ) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "process_sensor_reading",
            ProcessSensorReadingArgs {
                shipment_id,
                timestamp,
                temperature,
            },
        )
    }
    fn on_process_sensor_reading(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &i32, &__sdk::Timestamp, &f32)
            + Send
            + 'static,
    ) -> ProcessSensorReadingCallbackId {
        ProcessSensorReadingCallbackId(self.imp.on_reducer(
            "process_sensor_reading",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer:
                                super::Reducer::ProcessSensorReading {
                                    shipment_id,
                                    timestamp,
                                    temperature,
                                },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, shipment_id, timestamp, temperature)
            }),
        ))
    }
    fn remove_on_process_sensor_reading(&self, callback: ProcessSensorReadingCallbackId) {
        self.imp
            .remove_on_reducer("process_sensor_reading", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `process_sensor_reading`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_process_sensor_reading {
    /// Set the call-reducer flags for the reducer `process_sensor_reading` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn process_sensor_reading(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_process_sensor_reading for super::SetReducerFlags {
    fn process_sensor_reading(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("process_sensor_reading", flags);
    }
}
