// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.2 (commit 4b41cf3d71aa85cd4e75c96cbb54324481ee0b27).

#![allow(unused, clippy::all)]
use super::sensor_reading_type::SensorReading;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `sensor_reading`.
///
/// Obtain a handle from the [`SensorReadingTableAccess::sensor_reading`] method on [`super::RemoteTables`],
/// like `ctx.db.sensor_reading()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.sensor_reading().on_insert(...)`.
pub struct SensorReadingTableHandle<'ctx> {
    imp: __sdk::TableHandle<SensorReading>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `sensor_reading`.
///
/// Implemented for [`super::RemoteTables`].
pub trait SensorReadingTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`SensorReadingTableHandle`], which mediates access to the table `sensor_reading`.
    fn sensor_reading(&self) -> SensorReadingTableHandle<'_>;
}

impl SensorReadingTableAccess for super::RemoteTables {
    fn sensor_reading(&self) -> SensorReadingTableHandle<'_> {
        SensorReadingTableHandle {
            imp: self.imp.get_table::<SensorReading>("sensor_reading"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct SensorReadingInsertCallbackId(__sdk::CallbackId);
pub struct SensorReadingDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for SensorReadingTableHandle<'ctx> {
    type Row = SensorReading;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = SensorReading> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = SensorReadingInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SensorReadingInsertCallbackId {
        SensorReadingInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SensorReadingInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = SensorReadingDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SensorReadingDeleteCallbackId {
        SensorReadingDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SensorReadingDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<SensorReading>("sensor_reading");
    _table.add_unique_constraint::<i64>("id", |row| &row.id);
}
pub struct SensorReadingUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for SensorReadingTableHandle<'ctx> {
    type UpdateCallbackId = SensorReadingUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> SensorReadingUpdateCallbackId {
        SensorReadingUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: SensorReadingUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<SensorReading>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<SensorReading>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `sensor_reading`,
/// which allows point queries on the field of the same name
/// via the [`SensorReadingIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.sensor_reading().id().find(...)`.
pub struct SensorReadingIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<SensorReading, i64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> SensorReadingTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `sensor_reading`.
    pub fn id(&self) -> SensorReadingIdUnique<'ctx> {
        SensorReadingIdUnique {
            imp: self.imp.get_unique_constraint::<i64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> SensorReadingIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &i64) -> Option<SensorReading> {
        self.imp.find(col_val)
    }
}
