// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.2 (commit 4b41cf3d71aa85cd4e75c96cbb54324481ee0b27).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::lat_long_location_type::LatLongLocation;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Shipment {
    pub id: i32,
    pub content: String,
    pub status: String,
    pub min_temp: f32,
    pub max_temp: f32,
    pub current_temp: Option<f32>,
    pub start_location: LatLongLocation,
    pub current_location: LatLongLocation,
    pub end_location: LatLongLocation,
    pub sender_information: String,
    pub receiver_information: String,
    pub timestamp: __sdk::Timestamp,
    pub assigned_driver_id: Option<u64>,
}

impl __sdk::InModule for Shipment {
    type Module = super::RemoteModule;
}
