// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.2 (commit 4b41cf3d71aa85cd4e75c96cbb54324481ee0b27).

#![allow(unused, clippy::all)]
use super::lat_long_location_type::LatLongLocation;
use super::shipment_type::Shipment;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `shipment`.
///
/// Obtain a handle from the [`ShipmentTableAccess::shipment`] method on [`super::RemoteTables`],
/// like `ctx.db.shipment()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.shipment().on_insert(...)`.
pub struct ShipmentTableHandle<'ctx> {
    imp: __sdk::TableHandle<Shipment>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `shipment`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ShipmentTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ShipmentTableHandle`], which mediates access to the table `shipment`.
    fn shipment(&self) -> ShipmentTableHandle<'_>;
}

impl ShipmentTableAccess for super::RemoteTables {
    fn shipment(&self) -> ShipmentTableHandle<'_> {
        ShipmentTableHandle {
            imp: self.imp.get_table::<Shipment>("shipment"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ShipmentInsertCallbackId(__sdk::CallbackId);
pub struct ShipmentDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ShipmentTableHandle<'ctx> {
    type Row = Shipment;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Shipment> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ShipmentInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ShipmentInsertCallbackId {
        ShipmentInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ShipmentInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ShipmentDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ShipmentDeleteCallbackId {
        ShipmentDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ShipmentDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Shipment>("shipment");
    _table.add_unique_constraint::<i32>("id", |row| &row.id);
}
pub struct ShipmentUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ShipmentTableHandle<'ctx> {
    type UpdateCallbackId = ShipmentUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ShipmentUpdateCallbackId {
        ShipmentUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ShipmentUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Shipment>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Shipment>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `shipment`,
/// which allows point queries on the field of the same name
/// via the [`ShipmentIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.shipment().id().find(...)`.
pub struct ShipmentIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Shipment, i32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ShipmentTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `shipment`.
    pub fn id(&self) -> ShipmentIdUnique<'ctx> {
        ShipmentIdUnique {
            imp: self.imp.get_unique_constraint::<i32>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ShipmentIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &i32) -> Option<Shipment> {
        self.imp.find(col_val)
    }
}
