// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.2 (commit 4b41cf3d71aa85cd4e75c96cbb54324481ee0b27).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";

import { LatLongLocation as __LatLongLocation } from "./lat_long_location_type";

export type CreateShipment = {
  id: number,
  content: string,
  status: string,
  minTemp: number,
  maxTemp: number,
  startLocation: __LatLongLocation,
  currentLocation: __LatLongLocation,
  endLocation: __LatLongLocation,
  senderInformation: string,
  receiverInformation: string,
  timestamp: Timestamp,
};

/**
 * A namespace for generated helper functions.
 */
export namespace CreateShipment {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("id", AlgebraicType.createI32Type()),
      new ProductTypeElement("content", AlgebraicType.createStringType()),
      new ProductTypeElement("status", AlgebraicType.createStringType()),
      new ProductTypeElement("minTemp", AlgebraicType.createF32Type()),
      new ProductTypeElement("maxTemp", AlgebraicType.createF32Type()),
      new ProductTypeElement("startLocation", __LatLongLocation.getTypeScriptAlgebraicType()),
      new ProductTypeElement("currentLocation", __LatLongLocation.getTypeScriptAlgebraicType()),
      new ProductTypeElement("endLocation", __LatLongLocation.getTypeScriptAlgebraicType()),
      new ProductTypeElement("senderInformation", AlgebraicType.createStringType()),
      new ProductTypeElement("receiverInformation", AlgebraicType.createStringType()),
      new ProductTypeElement("timestamp", AlgebraicType.createTimestampType()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: CreateShipment): void {
    CreateShipment.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): CreateShipment {
    return CreateShipment.getTypeScriptAlgebraicType().deserialize(reader);
  }

}

