// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.2 (commit 4b41cf3d71aa85cd4e75c96cbb54324481ee0b27).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";

// Import and reexport all reducer arg types
import { AssignDriverToShipment } from "./assign_driver_to_shipment_reducer.ts";
export { AssignDriverToShipment };
import { CreateDriver } from "./create_driver_reducer.ts";
export { CreateDriver };
import { CreateShipment } from "./create_shipment_reducer.ts";
export { CreateShipment };
import { ProcessSensorReading } from "./process_sensor_reading_reducer.ts";
export { ProcessSensorReading };

// Import and reexport all table handle types
import { AlertTableHandle } from "./alert_table.ts";
export { AlertTableHandle };
import { DriverTableHandle } from "./driver_table.ts";
export { DriverTableHandle };
import { SensorReadingTableHandle } from "./sensor_reading_table.ts";
export { SensorReadingTableHandle };
import { ShipmentTableHandle } from "./shipment_table.ts";
export { ShipmentTableHandle };

// Import and reexport all types
import { Alert } from "./alert_type.ts";
export { Alert };
import { LatLongLocation } from "./lat_long_location_type.ts";
export { LatLongLocation };
import { SensorReading } from "./sensor_reading_type.ts";
export { SensorReading };
import { Shipment } from "./shipment_type.ts";
export { Shipment };
import { Transporter } from "./transporter_type.ts";
export { Transporter };

const REMOTE_MODULE = {
  tables: {
    alert: {
      tableName: "alert",
      rowType: Alert.getTypeScriptAlgebraicType(),
      primaryKey: "id",
      primaryKeyInfo: {
        colName: "id",
        colType: Alert.getTypeScriptAlgebraicType().product.elements[0].algebraicType,
      },
    },
    driver: {
      tableName: "driver",
      rowType: Transporter.getTypeScriptAlgebraicType(),
      primaryKey: "id",
      primaryKeyInfo: {
        colName: "id",
        colType: Transporter.getTypeScriptAlgebraicType().product.elements[0].algebraicType,
      },
    },
    sensor_reading: {
      tableName: "sensor_reading",
      rowType: SensorReading.getTypeScriptAlgebraicType(),
      primaryKey: "id",
      primaryKeyInfo: {
        colName: "id",
        colType: SensorReading.getTypeScriptAlgebraicType().product.elements[0].algebraicType,
      },
    },
    shipment: {
      tableName: "shipment",
      rowType: Shipment.getTypeScriptAlgebraicType(),
      primaryKey: "id",
      primaryKeyInfo: {
        colName: "id",
        colType: Shipment.getTypeScriptAlgebraicType().product.elements[0].algebraicType,
      },
    },
  },
  reducers: {
    assign_driver_to_shipment: {
      reducerName: "assign_driver_to_shipment",
      argsType: AssignDriverToShipment.getTypeScriptAlgebraicType(),
    },
    create_driver: {
      reducerName: "create_driver",
      argsType: CreateDriver.getTypeScriptAlgebraicType(),
    },
    create_shipment: {
      reducerName: "create_shipment",
      argsType: CreateShipment.getTypeScriptAlgebraicType(),
    },
    process_sensor_reading: {
      reducerName: "process_sensor_reading",
      argsType: ProcessSensorReading.getTypeScriptAlgebraicType(),
    },
  },
  versionInfo: {
    cliVersion: "1.3.2",
  },
  // Constructors which are used by the DbConnectionImpl to
  // extract type information from the generated RemoteModule.
  //
  // NOTE: This is not strictly necessary for `eventContextConstructor` because
  // all we do is build a TypeScript object which we could have done inside the
  // SDK, but if in the future we wanted to create a class this would be
  // necessary because classes have methods, so we'll keep it.
  eventContextConstructor: (imp: DbConnectionImpl, event: Event<Reducer>) => {
    return {
      ...(imp as DbConnection),
      event
    }
  },
  dbViewConstructor: (imp: DbConnectionImpl) => {
    return new RemoteTables(imp);
  },
  reducersConstructor: (imp: DbConnectionImpl, setReducerFlags: SetReducerFlags) => {
    return new RemoteReducers(imp, setReducerFlags);
  },
  setReducerFlagsConstructor: () => {
    return new SetReducerFlags();
  }
}

// A type representing all the possible variants of a reducer.
export type Reducer = never
| { name: "AssignDriverToShipment", args: AssignDriverToShipment }
| { name: "CreateDriver", args: CreateDriver }
| { name: "CreateShipment", args: CreateShipment }
| { name: "ProcessSensorReading", args: ProcessSensorReading }
;

export class RemoteReducers {
  constructor(private connection: DbConnectionImpl, private setCallReducerFlags: SetReducerFlags) {}

  assignDriverToShipment(shipmentId: number, driverId: bigint) {
    const __args = { shipmentId, driverId };
    let __writer = new BinaryWriter(1024);
    AssignDriverToShipment.getTypeScriptAlgebraicType().serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("assign_driver_to_shipment", __argsBuffer, this.setCallReducerFlags.assignDriverToShipmentFlags);
  }

  onAssignDriverToShipment(callback: (ctx: ReducerEventContext, shipmentId: number, driverId: bigint) => void) {
    this.connection.onReducer("assign_driver_to_shipment", callback);
  }

  removeOnAssignDriverToShipment(callback: (ctx: ReducerEventContext, shipmentId: number, driverId: bigint) => void) {
    this.connection.offReducer("assign_driver_to_shipment", callback);
  }

  createDriver(id: bigint, status: string, currentLocation: LatLongLocation) {
    const __args = { id, status, currentLocation };
    let __writer = new BinaryWriter(1024);
    CreateDriver.getTypeScriptAlgebraicType().serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("create_driver", __argsBuffer, this.setCallReducerFlags.createDriverFlags);
  }

  onCreateDriver(callback: (ctx: ReducerEventContext, id: bigint, status: string, currentLocation: LatLongLocation) => void) {
    this.connection.onReducer("create_driver", callback);
  }

  removeOnCreateDriver(callback: (ctx: ReducerEventContext, id: bigint, status: string, currentLocation: LatLongLocation) => void) {
    this.connection.offReducer("create_driver", callback);
  }

  createShipment(id: number, content: string, minTemp: number, maxTemp: number, startLocation: LatLongLocation, endLocation: LatLongLocation, senderInformation: string, receiverInformation: string) {
    const __args = { id, content, minTemp, maxTemp, startLocation, endLocation, senderInformation, receiverInformation };
    let __writer = new BinaryWriter(1024);
    CreateShipment.getTypeScriptAlgebraicType().serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("create_shipment", __argsBuffer, this.setCallReducerFlags.createShipmentFlags);
  }

  onCreateShipment(callback: (ctx: ReducerEventContext, id: number, content: string, minTemp: number, maxTemp: number, startLocation: LatLongLocation, endLocation: LatLongLocation, senderInformation: string, receiverInformation: string) => void) {
    this.connection.onReducer("create_shipment", callback);
  }

  removeOnCreateShipment(callback: (ctx: ReducerEventContext, id: number, content: string, minTemp: number, maxTemp: number, startLocation: LatLongLocation, endLocation: LatLongLocation, senderInformation: string, receiverInformation: string) => void) {
    this.connection.offReducer("create_shipment", callback);
  }

  processSensorReading(shipmentId: number, timestamp: Timestamp, temperature: number) {
    const __args = { shipmentId, timestamp, temperature };
    let __writer = new BinaryWriter(1024);
    ProcessSensorReading.getTypeScriptAlgebraicType().serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("process_sensor_reading", __argsBuffer, this.setCallReducerFlags.processSensorReadingFlags);
  }

  onProcessSensorReading(callback: (ctx: ReducerEventContext, shipmentId: number, timestamp: Timestamp, temperature: number) => void) {
    this.connection.onReducer("process_sensor_reading", callback);
  }

  removeOnProcessSensorReading(callback: (ctx: ReducerEventContext, shipmentId: number, timestamp: Timestamp, temperature: number) => void) {
    this.connection.offReducer("process_sensor_reading", callback);
  }

}

export class SetReducerFlags {
  assignDriverToShipmentFlags: CallReducerFlags = 'FullUpdate';
  assignDriverToShipment(flags: CallReducerFlags) {
    this.assignDriverToShipmentFlags = flags;
  }

  createDriverFlags: CallReducerFlags = 'FullUpdate';
  createDriver(flags: CallReducerFlags) {
    this.createDriverFlags = flags;
  }

  createShipmentFlags: CallReducerFlags = 'FullUpdate';
  createShipment(flags: CallReducerFlags) {
    this.createShipmentFlags = flags;
  }

  processSensorReadingFlags: CallReducerFlags = 'FullUpdate';
  processSensorReading(flags: CallReducerFlags) {
    this.processSensorReadingFlags = flags;
  }

}

export class RemoteTables {
  constructor(private connection: DbConnectionImpl) {}

  get alert(): AlertTableHandle {
    return new AlertTableHandle(this.connection.clientCache.getOrCreateTable<Alert>(REMOTE_MODULE.tables.alert));
  }

  get driver(): DriverTableHandle {
    return new DriverTableHandle(this.connection.clientCache.getOrCreateTable<Transporter>(REMOTE_MODULE.tables.driver));
  }

  get sensorReading(): SensorReadingTableHandle {
    return new SensorReadingTableHandle(this.connection.clientCache.getOrCreateTable<SensorReading>(REMOTE_MODULE.tables.sensor_reading));
  }

  get shipment(): ShipmentTableHandle {
    return new ShipmentTableHandle(this.connection.clientCache.getOrCreateTable<Shipment>(REMOTE_MODULE.tables.shipment));
  }
}

export class SubscriptionBuilder extends SubscriptionBuilderImpl<RemoteTables, RemoteReducers, SetReducerFlags> { }

export class DbConnection extends DbConnectionImpl<RemoteTables, RemoteReducers, SetReducerFlags> {
  static builder = (): DbConnectionBuilder<DbConnection, ErrorContext, SubscriptionEventContext> => {
    return new DbConnectionBuilder<DbConnection, ErrorContext, SubscriptionEventContext>(REMOTE_MODULE, (imp: DbConnectionImpl) => imp as DbConnection);
  }
  subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  }
}

export type EventContext = EventContextInterface<RemoteTables, RemoteReducers, SetReducerFlags, Reducer>;
export type ReducerEventContext = ReducerEventContextInterface<RemoteTables, RemoteReducers, SetReducerFlags, Reducer>;
export type SubscriptionEventContext = SubscriptionEventContextInterface<RemoteTables, RemoteReducers, SetReducerFlags>;
export type ErrorContext = ErrorContextInterface<RemoteTables, RemoteReducers, SetReducerFlags>;
